$(document).ready(function(){
    $('#registerToggle').click(function(){
        $('#login').hide();
        $('#register').fadeIn(1300);
    });
    $('#loginToggle').click(function(){
        $('#register').hide();
        $('#login').fadeIn(1300);
    });
});